### ISSUE TITLE
Segmentation Fault LMNN

### ISSUE THREAD

**Issue by mmabrouk** [all-umass/metric_learn#3]
Hello,

I get a segmentation fault when running LMNN.fit() with a big data set (~9000 data points, each an array of 27 floats). The LMNN.fit() function takes more than an hour to run and stop abruptly with a segmentation fault. In the mean time, the code starts taking bigger and bigger amounts of memory (>40G).
It seems that memory usage is behind the issue with segmentation fault.

Is there a way to optimize the code so that it does not use that much memory?

Yours,
Mahmoud

p.s. I am not using Modshogun.

**Comment by mmabrouk** [comment]
I was able to solve the issue by adding gc.collect() at the beginning of the main loop of lmnn.fit()
It seemed that the issue was that the array copies that were made each loop were not deleted afterwards.

**Comment by perimosocordiae** [comment]
This is interesting, thanks for bringing it to my attention.
